BEGIN TRANSACTION;
CREATE TABLE `Pages` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`url`	TEXT NOT NULL UNIQUE,
	`title`	TEXT,
	`created_at`	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Caches" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`page_id`	INTEGER NOT NULL,
	`html`	TEXT UNIQUE,
	`created_at`	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
COMMIT;
