BEGIN TRANSACTION;
CREATE TABLE `Page` (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`url`	TEXT NOT NULL UNIQUE,
	`created_at`	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE "Content" (
	`id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT UNIQUE,
	`page_id`	INTEGER NOT NULL,
	`html`	TEXT UNIQUE,
	`created_at`	TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(page_id) REFERENCES Page(id)
);
COMMIT;
